CREATE TABLE [dbo].[ActionsLog]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[Description] NVARCHAR(MAX) NOT NULL,
	[Operation] NVARCHAR(255) NOT NULL,
	[CreatedAt] DATETIME2 NOT NULL DEFAULT (GETUTCDATE()),
	[CreatedBy] NVARCHAR(255) NOT NULL
)
